<a href="https://colab.research.google.com/github/la-sarita/420-514_A24/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

In [ ]:
x = [1,2,3,4]
y = [10, 11, 12, 13]

In [ ]:
x

[1, 2, 3, 4]

In [ ]:
x + y

[1, 2, 3, 4, 10, 11, 12, 13]

In [ ]:
x * y

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
import numpy as np

In [ ]:
x1 = np.array(x)
y1 = np.array(y)

In [ ]:
x1

array([1, 2, 3, 4])

In [ ]:
y1

array([10, 11, 12, 13])

In [ ]:
type(x1)

numpy.ndarray

In [ ]:
x1 + y1

array([11, 13, 15, 17])

In [ ]:
x1 * y1

array([10, 22, 36, 52])

In [ ]:
y1 ** x1

array([   10,   121,  1728, 28561])

In [ ]:
print(x)
print(x1)

[1, 2, 3, 4]
[1 2 3 4]


In [ ]:
a1 = np.array([[1, 5, 7, 2], [2, 5, 6, 7]])

In [ ]:
a1

array([[1, 5, 7, 2],
       [2, 5, 6, 7]])

In [ ]:
print(a1)

[[1 5 7 2]
 [2 5 6 7]]


In [ ]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((2,3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.empty((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.empty((2,2), dtype = int)

array([[4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408]])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2 = np.arange(12)

In [ ]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a2.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a2.reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
a2 = a2.reshape(4,3)

In [ ]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.linspace(10, 0.2, 11)

array([10.  ,  9.02,  8.04,  7.06,  6.08,  5.1 ,  4.12,  3.14,  2.16,
        1.18,  0.2 ])

In [ ]:
np.linspace(start = 10, stop = 11, num = 50)

array([10.        , 10.02040816, 10.04081633, 10.06122449, 10.08163265,
       10.10204082, 10.12244898, 10.14285714, 10.16326531, 10.18367347,
       10.20408163, 10.2244898 , 10.24489796, 10.26530612, 10.28571429,
       10.30612245, 10.32653061, 10.34693878, 10.36734694, 10.3877551 ,
       10.40816327, 10.42857143, 10.44897959, 10.46938776, 10.48979592,
       10.51020408, 10.53061224, 10.55102041, 10.57142857, 10.59183673,
       10.6122449 , 10.63265306, 10.65306122, 10.67346939, 10.69387755,
       10.71428571, 10.73469388, 10.75510204, 10.7755102 , 10.79591837,
       10.81632653, 10.83673469, 10.85714286, 10.87755102, 10.89795918,
       10.91836735, 10.93877551, 10.95918367, 10.97959184, 11.        ])

In [ ]:
np.linspace(10, 11)

array([10.        , 10.02040816, 10.04081633, 10.06122449, 10.08163265,
       10.10204082, 10.12244898, 10.14285714, 10.16326531, 10.18367347,
       10.20408163, 10.2244898 , 10.24489796, 10.26530612, 10.28571429,
       10.30612245, 10.32653061, 10.34693878, 10.36734694, 10.3877551 ,
       10.40816327, 10.42857143, 10.44897959, 10.46938776, 10.48979592,
       10.51020408, 10.53061224, 10.55102041, 10.57142857, 10.59183673,
       10.6122449 , 10.63265306, 10.65306122, 10.67346939, 10.69387755,
       10.71428571, 10.73469388, 10.75510204, 10.7755102 , 10.79591837,
       10.81632653, 10.83673469, 10.85714286, 10.87755102, 10.89795918,
       10.91836735, 10.93877551, 10.95918367, 10.97959184, 11.        ])

In [ ]:
np.linspace(10, 11, 5)

array([10.  , 10.25, 10.5 , 10.75, 11.  ])

In [ ]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a2.ndim

2

In [ ]:
a2.reshape(2,2,3).ndim

3

In [ ]:
a2.shape

(4, 3)

In [ ]:
a2.reshape(2,2,3).shape

(2, 2, 3)

In [ ]:
a2.size

12

In [ ]:
a2.dtype

dtype('int64')

In [ ]:
np.linspace(10, 11).dtype

dtype('float64')

In [ ]:
a2.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
True & False

False

In [ ]:
True & True

True

In [ ]:
False & False

False

In [ ]:
True | True

True

In [ ]:
False | False

False

In [ ]:
a = np.arange(10)

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
2 * a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
a = a + 1

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.add(a, 1)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a**0

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
a**2 + a

array([  2,   6,  12,  20,  30,  42,  56,  72,  90, 110])

In [ ]:
a + a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b = np.arange(12)

In [ ]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a + b

ValueError: operands could not be broadcast together with shapes (10,) (12,) 

In [ ]:
a = a*2

In [ ]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
b = 2*a

In [ ]:
b

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [ ]:
a <= b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
a == b

array([False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
a < 7

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [ ]:
a == 10

array([False, False, False, False,  True, False, False, False, False,
       False])

In [ ]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
a[0]

2

In [ ]:
a2 = a2.reshape(3,4)

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0, 1]

1

In [ ]:
a2[:, 0]

array([0, 4, 8])

In [ ]:
a2[1, :]

array([4, 5, 6, 7])

In [ ]:
a2[:2, 1]

array([1, 5])

In [ ]:
a2[1, :2]

array([4, 5])

In [ ]:
a2[1, 0:2]

array([4, 5])

In [ ]:
a2[1, 1:3]

array([5, 6])

In [ ]:
a2[2, 1:]

array([ 9, 10, 11])

In [ ]:
a2[3,:]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [ ]:
a2[1,:6]

array([4, 5, 6, 7])

In [ ]:
a2[1,:]

array([4, 5, 6, 7])

In [ ]:
a2[1,6]

IndexError: index 6 is out of bounds for axis 1 with size 4

In [ ]:
a < 5

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [ ]:
a[a<5]

In [ ]:
a[a==10]

array([10])

In [ ]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
b = a.copy()

In [ ]:
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
a.argmax()

9

In [ ]:
a.argmin()

0

In [ ]:
a.min()

2

In [ ]:
a.max()

20

In [ ]:
h = a[a>10]

In [ ]:
h

array([12, 14, 16, 18, 20])

In [ ]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
a>20

array([False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
np.log(a)

array([0.69314718, 1.38629436, 1.79175947, 2.07944154, 2.30258509,
       2.48490665, 2.63905733, 2.77258872, 2.89037176, 2.99573227])

In [ ]:
np.mean(a)

11.0

In [ ]:
a.mean()

11.0

In [ ]:
np.floor(a/10)

array([0., 0., 0., 0., 1., 1., 1., 1., 1., 2.])

In [ ]:
c = np.concatenate((a, b))

In [ ]:
c

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20,  2,  4,  6,  8, 10, 12, 14,
       16, 18, 20])

In [ ]:
a.sum()

110

In [ ]:
np.std(a)

5.744562646538029

In [ ]:
# Matrices 2x2
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Multiplication de matrices (produit matriciel)
result = np.dot(matrix1, matrix2)
print(result)  # [[19, 22], [43, 50]]

# Transposition d'une matrice
transpose = np.transpose(matrix1)
print(transpose)  # [[1, 3], [2, 4]]


[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [ ]:
np.unique(c)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
matrix1

array([[1, 2],
       [3, 4]])

In [ ]:
reversed_arr_columns = np.flip(matrix1, axis=1)

In [ ]:
reversed_arr_columns

array([[2, 1],
       [4, 3]])

In [ ]:
reversed_arr_lines = np.flip(matrix1, axis=0)

In [ ]:
reversed_arr_lines

array([[3, 4],
       [1, 2]])

In [ ]:
matrix1.flatten()

array([1, 2, 3, 4])

In [ ]:
np.save('file1', a)

In [ ]:
loaded_array = np.load('file1.npy')

In [ ]:
loaded_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')